/**
 * Session types and interfaces for conversation persistence
 * Supports branching conversations stored as JSONL
 * Version 2: Added id/parentId tree structure, rich entry types
 */

// ============================================================================
// Session Version
// ============================================================================

export const CURRENT_SESSION_VERSION = 2;

// ============================================================================
// Entry Types
// ============================================================================

export interface SessionEntryBase {
  type: string;
  id: string;
  parentId: string | null;
  timestamp: number;
}

/** Standard message entry */
export interface SessionMessageEntry extends SessionEntryBase {
  type: "message";
  message: {
    role: "user" | "assistant" | "tool" | "system";
    content: string;
    toolName?: string;
    agentName?: string;
    provider?: string;
    model?: string;
  };
}

/** Thinking level change entry */
export interface ThinkingLevelChangeEntry extends SessionEntryBase {
  type: "thinking_level_change";
  thinkingLevel: "off" | "minimal" | "low" | "medium" | "high";
}

/** Model change entry */
export interface ModelChangeEntry extends SessionEntryBase {
  type: "model_change";
  provider: string;
  modelId: string;
}

/**
 * Compaction entry - summarizes older messages to save context space
 */
export interface CompactionEntry extends SessionEntryBase {
  type: "compaction";
  content: string;
  metadata: {
    /** ID of first entry kept after compaction */
    firstKeptEntryId: string;
    /** Token count before compaction */
    tokensBefore: number;
    /** Number of entries compacted */
    entriesCompacted: number;
    /** Files that were read (not modified) */
    readFiles: string[];
    /** Files that were modified or written */
    modifiedFiles: string[];
    /** Custom data from extensions */
    [key: string]: unknown;
  };
}

/** Branch summary entry - captures context from abandoned conversation path */
export interface BranchSummaryEntry extends SessionEntryBase {
  type: "branch_summary";
  content: string;
  metadata: {
    fromId: string;
    summary: string;
    /** Extension-specific data */
    details?: unknown;
    /** True if generated by an extension */
    fromHook?: boolean;
  };
}

/**
 * Custom entry for extensions to store extension-specific data.
 * Does NOT participate in LLM context.
 */
export interface CustomEntry extends SessionEntryBase {
  type: "custom";
  customType: string;
  data?: unknown;
}

/**
 * Custom message entry for extensions to inject messages into LLM context.
 * Unlike CustomEntry, this DOES participate in LLM context.
 */
export interface CustomMessageEntry extends SessionEntryBase {
  type: "custom_message";
  customType: string;
  content: string;
  display: boolean;
  details?: unknown;
}

/** Label entry for user-defined bookmarks/markers on entries */
export interface LabelEntry extends SessionEntryBase {
  type: "label";
  targetId: string;
  label: string | undefined;
}

/** Session metadata entry (e.g., user-defined display name) */
export interface SessionInfoEntry extends SessionEntryBase {
  type: "session_info";
  name?: string;
}

/** Legacy entry from v1 sessions (before tree structure) */
export interface LegacySessionEntry {
  id?: string;
  parentId?: string | null;
  type: "user" | "assistant" | "system" | "tool" | "delegation" | "label" | "compaction";
  content: string;
  toolName?: string;
  agentName?: string;
  timestamp: number;
  metadata?: Record<string, unknown>;
}

/** Union of all entry types */
export type SessionEntry =
  | SessionMessageEntry
  | ThinkingLevelChangeEntry
  | ModelChangeEntry
  | CompactionEntry
  | BranchSummaryEntry
  | CustomEntry
  | CustomMessageEntry
  | LabelEntry
  | SessionInfoEntry;

/** Raw file entry (includes header) */
export type FileEntry = SessionHeader | SessionEntry;

// ============================================================================
// Session Header
// ============================================================================

export interface SessionHeader {
  type: "session";
  version: number;
  id: string;
  timestamp: string;
  cwd: string;
  name?: string;
  parentSession?: string;
}

// ============================================================================
// Session Structure
// ============================================================================

export interface Session {
  /** Unique session identifier */
  id: string;
  /** Human-readable name */
  name: string;
  /** Working directory where session was created */
  cwd: string;
  /** When the session was created */
  createdAt: number;
  /** When the session was last modified */
  updatedAt: number;
  /** All entries in the session */
  entries: SessionEntry[];
  /** Currently active entry ID (for branching) */
  currentEntryId: string | null;
  /** Path to parent session if forked */
  parentSession?: string;
  /** Optional session metadata */
  metadata?: Record<string, unknown>;
}

// ============================================================================
// Session Summary (for listing)
// ============================================================================

export interface SessionSummary {
  id: string;
  name?: string;
  cwd: string;
  createdAt: number;
  updatedAt: number;
  entryCount: number;
  messageCount: number;
  firstMessage: string;
  allMessagesText: string;
  parentSessionPath?: string;
}

export interface SessionInfo {
  path: string;
  id: string;
  name?: string;
  cwd: string;
  parentSessionPath?: string;
  created: Date;
  modified: Date;
  messageCount: number;
  firstMessage: string;
  allMessagesText: string;
}

// ============================================================================
// Session Branch
// ============================================================================

export interface SessionBranch {
  /** Root entry of this branch */
  rootEntryId: string;
  /** All entries in this branch */
  entries: SessionEntry[];
  /** Current/leaf entry ID */
  currentEntryId: string;
}

/** Tree node for getTree() - defensive copy of session structure */
export interface SessionTreeNode {
  entry: SessionEntry;
  children: SessionTreeNode[];
  /** Resolved label for this entry, if any */
  label?: string;
}

// ============================================================================
// Session Context (for LLM)
// ============================================================================

export interface SessionContext {
  messages: Array<{
    role: string;
    content: string;
    toolName?: string;
    agentName?: string;
  }>;
  thinkingLevel: string;
  model: { provider: string; modelId: string } | null;
}

// ============================================================================
// Events
// ============================================================================

/** Event types for session changes */
export type SessionEventType =
  | "entry_added"
  | "entry_removed"
  | "branch_created"
  | "session_saved"
  | "session_loaded"
  | "session_renamed"
  | "session_compacted"
  | "label_changed"
  | "session_info_updated";

export interface SessionEvent {
  type: SessionEventType;
  sessionId: string;
  entryId?: string;
  data?: unknown;
}

export type SessionEventListener = (event: SessionEvent) => void;

// ============================================================================
// Progress Callbacks
// ============================================================================

export type SessionListProgress = (loaded: number, total: number) => void;

// ============================================================================
// Migration
// ============================================================================

/** v1 session entry (before tree structure) */
export interface V1SessionEntry {
  type: "user" | "assistant" | "system" | "tool" | "delegation" | "label" | "compaction";
  content: string;
  toolName?: string;
  agentName?: string;
  timestamp: number;
  metadata?: Record<string, unknown>;
}

/** v1 session (no id/parentId structure) */
export interface V1Session {
  id: string;
  name: string;
  createdAt: number;
  updatedAt: number;
  entries: V1SessionEntry[];
  currentEntryId: string | null;
  metadata?: Record<string, unknown>;
}

/** v2 session header */
export interface V2SessionHeader {
  type: "session";
  version: 2;
  id: string;
  timestamp: string;
  cwd: string;
  parentSession?: string;
}
